### ISSUE TITLE
[master] device-virtual fails at startup due to device creation failure

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-virtual-go#103]
The main edgex snap (edgexfoundry) includes device-virtual as it's useful for developers/users learning their way around EdgeX. This service is disabled by default.

When I enable device-virtual (`sudo snap set edgexfoundry device-virtual=on`), the service starts, however it fails creating Random-Binary-Device, which causes the service to terminate.

I rebuilt the snap this morning with all of my in-progress patches re-based on edgex-go latest master ([6d40726](https://github.com/edgexfoundry/edgex-go/commit/6d4072662fd20448464d6b9f1b6b045ced6f2767)) and device-virtual latest master ([b102ac6](https://github.com/edgexfoundry/device-virtual-go/commit/b102ac6fa70487e807dff5fd1cb20d5f5eede679)).

I haven't tried to reproduce this with docker, but will do so next...

Here's the relevant log output:

```
Started Service for snap application edgexfoundry.device-virtual.
INFO msg="Loaded configuration from /var/snap/edgexfoundry/x1/config/device-virtual/res/configuration.toml"
INFO msg="Environment override of 'Device.ProfilesDir' by environment variable: Device_ProfilesDir=/var/snap/edgexfoundry/x1/config/device-virtual/res"
INFO msg="Config Provider URL created from -r/-registry=<url> flag"
INFO msg="Using Configuration provider (consul) from: http://localhost:8500 with base path of edgex/core/1.0/device-virtual"
INFO msg="Configuration has been pushed to into Configuration Provider (1 environment overrides applied)"
ERROR msg="logTarget cannot be blank, using stdout only"
INFO msg="Using Registry (consul) from http://localhost:8500"
INFO msg="Writeable configuration has been updated from the Configuration Provider"
INFO msg="Web server starting (localhost:49990)"
INFO msg="Check Metadata service's status via Registry..."
INFO msg="Check Data service's status via Registry..."
INFO msg="Service clients initialize successful."
ERROR msg="no item found for supplied key: device-virtual"
INFO msg="Device Service device-virtual doesn't exist, creating a new one"
INFO msg="Addressable device-virtual doesn't exist, creating a new one"
ERROR msg="Device Profile Random-Binary-Device doesn't exist for Device Random-Binary-Device"
ERROR msg="creating Device from config failed: Random-Binary-Device"
Failed to create the pre-defined Devices: Device Profile Random-Binary-Device doesn't exist for Device Random-Binary-Device
INFO msg="Web server shutting down"
INFO msg="Web server shut down"
INFO Msg="Web server stopped"
INFO msg="Un-Registering service from the Registry"


```

**Comment by tonyespy** [comment]
I just tried the latest (as of today's developer-scripts) docker-compose-nexus-redis compose file and device-virtual is failing even earlier than in the snap:

```
ERROR app=device-virtual source=init.go:112 msg="service dependency Data checking time out"
ERROR app=device-virtual source=init.go:112 msg="service dependency Metadata checking time out"
error: checking required dependencied services failed 
INFO app=device-virtual source=httpserver.go:106 msg="Web server shutting down"
INFO app=device-virtual source=httpserver.go:108 msg="Web server shut down"
INFO app=device-virtual source=httpserver.go:97 msg="Web server stopped"

```

**Comment by cloudxxx8** [comment]
may I know which compose file you are using?  it looks like the core services did start up or can't be reached.

**Comment by hahattan** [comment]
For now the latest docker-compose-nexus-redis-no-secty works well. the secty one, I got the following error which is similar to edgexfoundry/edgex-go#2516
```
Couldn't register to metadata service: 500 - Could not dial Redis: ERR invalid password

level=ERROR ts=2020-04-27T15:55:12.0265664Z app=device-virtual source=service.go:86 msg="DeviceServicForName failed: 500 - Could not dial Redis: ERR invalid password\n"
```

**Comment by tonyespy** [comment]
> may I know which compose file you are using? it looks like the core services did start up or can't be reached.

docker-compose-nexus-redis

**Comment by hahattan** [comment]
> I just tried the latest (as of today's developer-scripts) docker-compose-nexus-redis compose file and device-virtual is failing even earlier than in the snap:
> 
> ```
> ERROR app=device-virtual source=init.go:112 msg="service dependency Data checking time out"
> ERROR app=device-virtual source=init.go:112 msg="service dependency Metadata checking time out"
> error: checking required dependencied services failed 
> INFO app=device-virtual source=httpserver.go:106 msg="Web server shutting down"
> INFO app=device-virtual source=httpserver.go:108 msg="Web server shut down"
> INFO app=device-virtual source=httpserver.go:97 msg="Web server stopped"
> ```

sometimes it took longer for the device service to do the health check on coredata and core-metadata (no matter via ping api or registry), and it usually because core services are also waiting for its dependency service, for example I got following logs in coredata:
```
level=INFO ts=2020-04-27T16:07:17.8910683Z app=edgex-core-data source=secret.go:67 msg="Reading secret store configuration and authentication token"
level=INFO ts=2020-04-27T16:07:17.8959305Z app=edgex-core-data source=secret.go:73 msg="Attempting to create secretclient"
level=WARN ts=2020-04-27T16:07:17.9440488Z app=edgex-core-data source=secret.go:82 msg="Retryable failure while creating SecretClient: HTTP response with status code 403, message: failed to lookup token"
```
and it retried like 6~7 times and finally succeed, during this period the device service exceed its connectionretries limit.

I think in this case we have no choice but to manually restart device-virtual..

**Comment by tonyespy** [comment]
> For now the latest docker-compose-nexus-redis-no-secty works well. the secty one, I still got the following error which is similar to [edgexfoundry/edgex-go#2516](https://github.com/edgexfoundry/edgex-go/issues/2516)
> 
> ```
> Couldn't register to metadata service: 500 - Could not dial Redis: ERR invalid password
> 
> level=ERROR ts=2020-04-27T15:55:12.0265664Z app=device-virtual source=service.go:86 msg="DeviceServicForName failed: 500 - Could not dial Redis: ERR invalid password\n"
> ```

Looks like you may have some old images cached on your system. I'd recommend delete any cached images and start from a fresh developer-scripts. The error that your seeing indicates that you may not have all the update security bits required to use redis securely.

**Comment by tonyespy** [comment]
OK, my original problem is caused by the fact the binary device profile wasn't being copied to $SNAP_DATA.

**Comment by tonyespy** [comment]
Based on my previous comment, I'm closing this issue.
