### ISSUE TITLE
Device-virtual fails when run with read-only root file system

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/device-virtual-go#119]
When started under docker with `read_only: true` the service fails with the following error:

```
Driver.Initialize failed: mkdir db: read-only file system
level=INFO ts=2020-07-21T20:17:51.174366781Z app=device-virtual source=virtualdriver.go:60 msg="mkdir failed: mkdir db: read-only file system"
```

**Comment by bnevis-i** [comment]
Notify security team when resolved so that updates can be made to docker-compose file.

**Comment by cloudxxx8** [comment]
@FelixTing may we make the db run only in memory, not on the disk?

**Comment by bnevis-i** [comment]
If the data needs to be persistent across container restarts, then the proper thing to do is mount a docker volume to an empty mount point in the container, which is either freshly initialized on startup, or state is recovered from that location upon startup.

**Comment by bnevis-i** [comment]
Also, if we know we need a writable area that is just scratch space, it is possible to use the tmpfs parameter to mount a temporary file system to that path that is purged across container restarts.
