### ISSUE TITLE
CRASH: device-virtual: fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-virtual-go#122]
this issue is moved from https://github.com/edgexfoundry/edgex-go/issues/2492

**Comment by cloudxxx8** [comment]
@brian-intel do you know how to reproduce this easily?
since we made several fixes recently, do you still see this issue?

**Comment by FelixTing** [comment]
Consider the date the original issue([edgex-go#2492](https://github.com/edgexfoundry/edgex-go/issues/2492)) created, I think this issue should have been resolved. See https://github.com/edgexfoundry/device-virtual-go/issues/101.

**Comment by lenny-intel** [comment]
> @brian-intel do you know how to reproduce this easily?
> since we made several fixes recently, do you still see this issue?

@bnevis-i , not brian-intel ;-)

**Comment by bnevis-i** [comment]
It's been four months.  I'd close it as cannot reproduce if you can't reproduce it.  It's a pretty safe bet that in four months my entire environment has changed and I will unlikely be able to get this to show up again.

**Comment by cloudxxx8** [comment]
@bnevis-i thanks for the confirmation
