### ISSUE TITLE
DS-Virtual: Switch to 2.0 Consul path

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-virtual-go#174]
Update to latest SDK that uses edgex/appservices/2.0/ root path in Consul.
This change are to go into effect on April 7th.

**Comment by lenny-intel** [comment]
@hahattan , once the SDK PR https://github.com/edgexfoundry/device-sdk-go/pull/864 is merged can you update the go.mod here with the latest SDK. THX!

I am getting strange compile issues due to ZMQ4 that I don't get on edgex-go or app-service-configurable. Hoping it has something to do with my system...

**Comment by lenny-intel** [comment]
@hahattan , @cloudxxx8 , looks like we have an issue with using the latest SDK in the device service.
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fdevice-virtual-go/detail/PR-178/1/pipeline

I see the same thing in my dev environment, but as stated above, not with edgex-go or app-service-configurable which are also using ZMQ4.

**Comment by hahattan** [comment]
I remembered seeing similar issue before ...

https://github.com/edgexfoundry/device-sdk-go/commit/0b2e4f38269b961668004c74e6c331d44d6cde85
this commit was added to fix the issue, I'll update the related files if necessary
