### ISSUE TITLE
device-vierual-go:The virtual device cannot start

### ISSUE THREAD

**Issue by FengZeHe** [edgexfoundry/device-virtual-go#175]
Today i clone the virtual device from https://github.com/edgexfoundry/device-virtual-go ,but it cannot boot.
Terminal print some logs: **"app=device-virtual source=secret.go:51 msg="Creating SecretClient""**
**app=device-virtual source=secret.go:58 msg="Reading secret store configuration and authentication token"**
**app=device-virtual source=secret.go:70 msg="Attempting to create secret client"**
**app=device-virtual source=secret.go:80 msg="Retryable failure while creating SecretClient: invalid secrets client type of ''"**

But i run other program like "device-simple" ,it can run as usual.
I have run this program before without this problem,that is weird.

**Comment by cloudxxx8** [comment]
master branch is under development, so please use v1.3.1 tag to run with Hanoi core services

**Comment by FengZeHe** [comment]
> master branch is under development, so please use v1.3.1 tag to run with Hanoi core services
thank a lot
