### ISSUE TITLE
Ping check is always 404, when I use owner docker images, What's the problem？

### ISSUE THREAD

**Issue by yfj86912** [edgexfoundry/device-virtual-go#190]
I use version 1.3.1 
when i build my docker image, ping check is always 404, what can I do?

**Comment by cloudxxx8** [comment]
please provide the recreate steps.  what is your ping URL?

**Comment by yfj86912** [comment]
1. docker-compose-hanoi-arm64.yml
...  
device-virtual:
    container_name: edgex-device-virtual
    depends_on:
    - consul
    - data
    - metadata
    environment:
      CLIENTS_COMMAND_HOST: edgex-core-command
      CLIENTS_COREDATA_HOST: edgex-core-data
      CLIENTS_DATA_HOST: edgex-core-data
      CLIENTS_METADATA_HOST: edgex-core-metadata
      CLIENTS_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_RULESENGINE_HOST: edgex-kuiper
      CLIENTS_SCHEDULER_HOST: edgex-support-scheduler
      CLIENTS_VIRTUALDEVICE_HOST: edgex-device-virtual
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-device-virtual
    hostname: edgex-device-virtual
    image: edgexfoundry/docker-device-virtual-go-arm64:1.3.1
    networks:
      edgex-network: {}
    ports:
    - 49990:49990/tcp
    
the device-virtual is ok, the Health check is ok.

2. I use release code 1.3.1, and run 'make docker' build edgexfoundry/docker-device-virtual-go:0.0.0-dev  image.
3. change image to edgexfoundry/docker-device-virtual-go:0.0.0-dev
4. In Edgex-compose and run 'make run arm64'
then health cheak get "HTTP GET http://edgex-device-virtual:49990/api/v1/ping: 404 Not Found Output: 404 page not found"

![image](https://user-images.githubusercontent.com/5157749/115681260-f23d9780-a386-11eb-84a7-8004730ff006.png)

**Comment by lenny-intel** [comment]
@yfj86912 , did you mean to close this issue?

**Comment by lenny-intel** [comment]
Ping is working fine with `docker-compose-hanoi.yml`
![image](https://user-images.githubusercontent.com/44779287/115745826-09619280-a351-11eb-8b43-dc26ebe4e673.png)
Verify the service is actually running.
