### ISSUE TITLE
Why are devices and services automatically generated ?

### ISSUE THREAD

**Issue by FengZeHe** [edgexfoundry/device-virtual-go#238]
Hello. Good morning.
I removed devices like random-Boolea-device, Random-Integer-Device,Random-UnsignedInteger-Device,Random-Float-Device,Random-Binary-Device ,and delete profiles. 
I also removed the device-Virtual service from the Dockerfile.

When I rebooted my computer, all the devices came back.
Please tell me how to deal with it, thank you !!

**Comment by cloudxxx8** [comment]
this design is for the convivence of test and development.
you can disable it anytime. all the device service can use the pre-defined profiles and devices.
you just need to set the following configuration to the empty string:

ProfilesDir = ""
DevicesDir = ""

By the default, the service will always load them from those folders:
https://github.com/edgexfoundry/device-virtual-go/blob/60d9a57dff39513032cce8af6e955f5a8a0738df/cmd/res/configuration.toml#L74-L75

You can also define environment variable from docker-compose file to override them:
```
DEVICE_PROFILESDIR=
DEVICE_DEVICESDIR=
```

**Comment by FengZeHe** [comment]
> this design is for the convivence of test and development.
> you can disable it anytime. all the device service can use the pre-defined profiles and devices.
> you just need to set the following configuration to the empty string:
> 
> ProfilesDir = ""
> DevicesDir = ""
> 
> By the default, the service will always load them from those folders:
> https://github.com/edgexfoundry/device-virtual-go/blob/60d9a57dff39513032cce8af6e955f5a8a0738df/cmd/res/configuration.toml#L74-L75
> 
> You can also define environment variable from docker-compose file to override them:
> 
> ```
> DEVICE_PROFILESDIR=
> DEVICE_DEVICESDIR=
> ```
Thank you !! I solved the problem
