### ISSUE TITLE
Changing the frequency of messages generated by device-virtual

### ISSUE THREAD

**Issue by Rohini8** [edgexfoundry/device-virtual-go#253]
We are running the device-virtual as a service in edgex framework as per the link https://docs.edgexfoundry.org/2.0/getting-started/quick-start/ .As the service is mentioned in docker-compose.yml file, docker fetches the source code of device virtual as a container. 
We are trying to change the frequency of messages generated by the device. So edited the devices.toml file in the docker container of device virtual. But its not reflecting in the HiveMQ broker. 

Please let us know that how to change the frequency of messages when device-virtual is running through docker container.
Hereby attaching the docker-compose.yml file
[docker-compose.yml.txt](https://github.com/edgexfoundry/device-virtual-go/files/7560946/docker-compose.yml.txt)
.

**Comment by cloudxxx8** [comment]
After the service first starting up, the Devices have been created into core-metadata, so the change in the device.toml won't work.
You can add a volume mapping to your custom device.toml into the docker-compose file, like `<your folder>:/res/device`
In this case, the service will load your device.toml when the service starts up.

**Comment by Rohini8** [comment]
I tried adding volumes in device-virtual service like this :
device-virtual:
    container_name: edgex-device-virtual
    depends_on:
    - consul
    - data
    - metadata
    environment:
      CLIENTS_CORE_COMMAND_HOST: edgex-core-command
      CLIENTS_CORE_DATA_HOST: edgex-core-data
      CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      CLIENTS_SUPPORT_NOTIFICATIONS_HOST: edgex-support-notifications
      CLIENTS_SUPPORT_SCHEDULER_HOST: edgex-support-scheduler
      DATABASES_PRIMARY_HOST: edgex-redis
      EDGEX_SECURITY_SECRET_STORE: "false"
      MESSAGEQUEUE_HOST: edgex-redis
      REGISTRY_HOST: edgex-core-consul
      SERVICE_HOST: edgex-device-virtual
    hostname: edgex-device-virtual
    image: edgexfoundry/device-virtual:2.0.0
    networks:
      edgex-network: {}
    ports:
    - 127.0.0.1:59900:59900/tcp
    read_only: false
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    **volumes:
    - devices:/res/devices**
**volumes:
  devices: {}**   
But still change in frequency is not reflecting. Please let me know whether the approach is right.

**Comment by cloudxxx8** [comment]
your source volume is named volume, not from your home directory.
please use absolute path for the source folder, such /home/user/devices
