### ISSUE TITLE
Got error "Failed to subscribe internal command request" while deploying device-virtual

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/device-virtual-go#307]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: device-virtual

### Is this a regression?

 Yes

### Description and Minimal Reproduction [**REQUIRED**]
Deploy edgex with [taf mqtt-bus compose file](https://github.com/edgexfoundry/edgex-compose/blob/19612e4f16a9059524fb46ab1dc066da0ef66724/taf/docker-compose-taf-no-secty-mqtt-bus.yml)

## 🔥 Exception or Error
<pre><code>

Start device-virtual fail and got below error.
"Failed to subscribe internal command request: An error occured while performing a 'Subscribe' operation: invalid Topic; empty string"
</code></pre>

## 🌍  Your Environment
**Deployment Environment:** ubuntu

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
@hahattan please help add the following configs to each go device service
```
  [MessageQueue.Topics]
  CommandRequestTopic = "edgex/command/request/#"         # subscribing for inbound command requests
  CommandResponseTopicPrefix = "edgex/command/response"   # publishing outbound command responses; <device-service>/<device-name>/<command-name>/<method> will be added to this publish topic prefix

```

Also, for backward compatibility, you need to modify SDK to skip the message bus subscrption if the `CommandRequestTopic` doesn't exist.

**Comment by cloudxxx8** [comment]
sorry, I just noticed the backward compatibility issue doesn't exist, because the older version won't use the new sdk.

**Comment by cherrycl** [comment]
We got different error for Redis bus.

1. Deploy with [redis bus compose file](https://github.com/edgexfoundry/edgex-compose/blob/19612e4f16a9059524fb46ab1dc066da0ef66724/taf/docker-compose-taf-no-secty.yml)
2. Modify UseMessageBus to false from consul > device-virtual > device
3. Restart device-virtual
4. device-virtual fails to restart and found the below error on logs.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x56151a4d673c]

goroutine 1 [running]:
github.com/edgexfoundry/device-sdk-go/v2/internal/controller/messaging.SubscribeCommands({0x56151a863280?, 0xc000355940}, 0xc0003ee140)
	github.com/edgexfoundry/device-sdk-go/v2@v2.3.0-dev.26/internal/controller/messaging/command.go:51 +0x29c
github.com/edgexfoundry/device-sdk-go/v2/pkg/service.(*Bootstrap).BootstrapHandler(0xc000428470?, {0x56151a863280?, 0xc000355940}, 0xc00037f800, {{0xc0c4c88f57333e3c, 0x49c6b4, 0x56151ad8a100}, 0xdf8475800, 0x3b9aca00}, 0xc0003ee140)
	github.com/edgexfoundry/device-sdk-go/v2@v2.3.0-dev.26/pkg/service/init.go:83 +0x64b
github.com/edgexfoundry/go-mod-bootstrap/v2/bootstrap.RunAndReturnWaitGroup({0x56151a863280, 0xc000355940}, 0xc0003e84a0, {0x56151a866448?, 0xc000076ae0}, {0x56151a56b78b, 0xe}, {0x56151a56b7d1, 0xe}, {0x56151a8663f0, ...}, ...)
	github.com/edgexfoundry/go-mod-bootstrap/v2@v2.3.0-dev.16/bootstrap/bootstrap.go:158 +0x7de
github.com/edgexfoundry/go-mod-bootstrap/v2/bootstrap.Run({0x56151a863280?, 0xc000355940?}, 0xc0003e84a0, {0x56151a866448?, 0xc000076ae0?}, {0x56151a56b78b?, 0x7fa5dd58bc00?}, {0x56151a56b7d1?, 0xc0000524a8?}, {0x56151a8663f0, ...}, ...)
	github.com/edgexfoundry/go-mod-bootstrap/v2@v2.3.0-dev.16/bootstrap/bootstrap.go:184 +0x105
github.com/edgexfoundry/device-sdk-go/v2/pkg/service.Main({0x56151a56b78b, 0xe}, {0x56151a68d570, 0xc}, {0x56151a7e4ee0, 0xc00036ed70}, {0x56151a863280, 0xc000355940}, 0xc00029fee0?, 0xc0002e9d40)
	github.com/edgexfoundry/device-sdk-go/v2@v2.3.0-dev.26/pkg/service/main.go:70 +0x87b
github.com/edgexfoundry/device-sdk-go/v2/pkg/startup.Bootstrap({0x56151a56b78b, 0xe}, {0x56151a68d570, 0xc}, {0x56151a7e4ee0, 0xc00036ed70})
	github.com/edgexfoundry/device-sdk-go/v2@v2.3.0-dev.26/pkg/startup/bootstrap.go:19 +0xef
main.main()
	github.com/edgexfoundry/device-virtual-go/cmd/main.go:22 +0x47
```

**Comment by cloudxxx8** [comment]
this should be resolved after upgrading the sdk

**Comment by cherrycl** [comment]
This issue was fixed.
