### ISSUE TITLE
Replace the deprecated function rand.Seed

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-virtual-go#358]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for device-virtual

### Description [**REQUIRED**]
rand.Seed function is deprecated in golang v1.20
https://pkg.go.dev/math/rand#Seed

We had better replace the usage in this repository

### Describe the solution you'd like
Try to use Rand.Seed instead
https://pkg.go.dev/math/rand#Rand.Seed

**Comment by lenny-intel** [comment]
@cloudxxx8 , thanks for creating this. There is also other use of math/rand that needs to be replaced also with the seed code.

**Comment by jinlinGuan** [comment]
According to https://github.com/golang/go/issues/54880, the generator is seeded randomly at program startup now. Should we just remove `rand.Seed `?
