### ISSUE TITLE
Core-Data: media type must be specified for binary values

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/device-virtual-go#92]
1. download [nightly build compose file](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml)
`docker-compose -f docker-compose-nexus-redis-no-secty.yml up -d`
2. `curl -X GET http://localhost:48080/api/v1/reading `

Got the following error in core-data log:
```
level=ERROR ts=2020-03-17T07:38:31.657394Z app=edgex-core-data source=reading.go:37 msg="media type must be specified for binary values"
level=ERROR ts=2020-03-17T07:38:31.6595081Z app=edgex-core-data source=handler.go:47 msg="media type must be specified for binary values"
```

**Comment by cloudxxx8** [comment]
@FelixTing please see this is the issue in device-virtual or device-sdk-go

**Comment by FelixTing** [comment]
This is related to https://github.com/edgexfoundry/device-sdk-go/issues/465

**Comment by cloudxxx8** [comment]
close this issue, and assign edgexfoundry/device-sdk-go#465 to @weichou1229
